// get list of all 150 pokemons
const GET_LIST_POKEMON         = 'GET_POKEMON';
const GET_LIST_POKEMON_SUCCES  = 'GET_POKEMON_SUCCES';
const GET_LIST_POKEMON_ERROR   = 'GET_POKEMON_ERROR';

// get a pokemon
const GET_POKEMON         = 'GET_POKEMON';
const GET_POKEMON_SUCCES  = 'GET_POKEMON_SUCCES';
const GET_POKEMON_ERROR   = 'GET_POKEMON_ERROR';
